name: Test
env:
  DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/test

on:
  pull_request:
    branches: ["main"]
jobs:
  Deploy-Preview:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install
        run: pnpm i
      - name: Test
        run: pnpm test:ci
